spring.application.name=skill-7-exp
spring.jpa.hibernate.ddl-auto=update
spring.datasource.dbcp2.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/klus5
spring.datasource.username=root
spring.datasource.password=OnlyPass@22
spring.jpa.show-sql=true
server.port=8080